apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-web.fullname" . }}
  labels:
    {{- include "devops-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  ADMIN_USER: {{ .Values.secrets.adminUser | quote }}
  ADMIN_PASS: {{ .Values.secrets.adminPass | quote }}
  SMTP_USER: {{ .Values.secrets.smtpUser | quote }}
  SMTP_PASS: {{ .Values.secrets.smtpPass | quote }}
  EMAIL_TO: {{ .Values.secrets.emailTo | quote }}
